import {
  Home,
  ShoppingCart,
  Plug,
  Car,
  UtensilsCrossed,
  HeartPulse,
  Clapperboard,
  ShoppingBag,
  PiggyBank,
  Plane,
  Receipt,
  Folder,
  House,
  Building,
  Building2,
  Warehouse,
  Landmark,
  Key,
  DoorOpen,
  Lamp,
  Lightbulb,
  Zap,
  Droplet,
  Droplets,
  Flame,
  Thermometer,
  Wifi,
  Router,
  Tv,
  Fan,
  AirVent,
  Refrigerator,
  WashingMachine,
  Sofa,
  Armchair,
  Bed,
  Bath,
  ShowerHead,
  Toilet,
  Wrench,
  Hammer,
  PaintRoller,
  Paintbrush,
  Trees,
  Flower,
  Leaf,
  Sprout,
  Fence,
  Store,
  Package,
  Shirt,
  Footprints,
  Gem,
  Watch,
  Gift,
  Tag,
  Percent,
  Utensils,
  Coffee,
  Pizza,
  Beer,
  Wine,
  IceCreamCone,
  Cake,
  Croissant,
  Soup,
  Fish,
  Beef,
  Apple,
  Carrot,
  Bus,
  TrainFront,
  Fuel,
  Bike,
  Ship,
  ParkingCircle,
  Route,
  MapPin,
  Navigation,
  Stethoscope,
  Pill,
  Syringe,
  Cross,
  Activity,
  Dumbbell,
  Glasses,
  Smile,
  Baby,
  Film,
  Music,
  Music2,
  Gamepad,
  Gamepad2,
  Ticket,
  PartyPopper,
  Camera,
  Popcorn,
  Dice5,
  Palette,
  Book,
  BookOpen,
  GraduationCap,
  Backpack,
  Pencil,
  School,
  Briefcase,
  Laptop,
  Smartphone,
  Headphones,
  Monitor,
  Printer,
  HardDrive,
  Wallet,
  CreditCard,
  Banknote,
  Coins,
  TrendingUp,
  TrendingDown,
  LineChart,
  BarChart3,
  Calculator,
  DollarSign,
  Euro,
  Vault,
  HandCoins,
  Dog,
  Cat,
  PawPrint,
  Bone,
  Bird,
  Users,
  User,
  Heart,
  Church,
  Umbrella,
  CloudRain,
  Sun,
  Snowflake,
  Luggage,
  Compass,
  Globe,
  Tent,
  Mountain,
  Palmtree,
  Sailboat,
  Anchor,
  FolderOpen,
  Archive,
  Boxes,
  Recycle,
  Truck,
  Bolt,
  Settings,
  Star,
  Sparkles,
  Award,
  Trophy,
  Target,
  Flag,
  Shield,
  ShieldCheck,
  Scale,
  Scissors,
  Brush,
  Wand2,
  Bell,
  Phone,
  Mail,
  MessageCircle,
  Video,
  Radio,
  Newspaper,
  type LucideIcon,
} from "lucide-react";
import { createElement } from "react";
import { cn } from "./utils";

/**
 * Category icon library sourced entirely from lucide-react (ADR 0007: a
 * keyed lucide map replacing freeform emoji, single violet tile, no
 * per-category palette). Keys are stable lowercase strings stored in
 * `Category.icon` / `SavingsGoal.icon` — never rename an existing key.
 *
 * Grouped for the picker's browse view; `CATEGORY_ICONS` below is the
 * flattened key→icon lookup used everywhere else.
 */
export const CATEGORY_ICON_GROUPS: {
  label: string;
  icons: Record<string, LucideIcon>;
}[] = [
  {
    label: "General",
    icons: {
      rent: Home,
      groceries: ShoppingCart,
      utilities: Plug,
      transport: Car,
      food: UtensilsCrossed,
      health: HeartPulse,
      entertainment: Clapperboard,
      shopping: ShoppingBag,
      savings: PiggyBank,
      travel: Plane,
      bills: Receipt,
      other: Folder,
    },
  },
  {
    label: "Home & Utilities",
    icons: {
      house: House,
      building: Building,
      office: Building2,
      warehouse: Warehouse,
      landmark: Landmark,
      key: Key,
      door: DoorOpen,
      lamp: Lamp,
      lightbulb: Lightbulb,
      zap: Zap,
      droplet: Droplet,
      droplets: Droplets,
      flame: Flame,
      thermometer: Thermometer,
      wifi: Wifi,
      router: Router,
      tv: Tv,
      fan: Fan,
      "air-vent": AirVent,
      fridge: Refrigerator,
      "washing-machine": WashingMachine,
      sofa: Sofa,
      armchair: Armchair,
      bed: Bed,
      bath: Bath,
      shower: ShowerHead,
      toilet: Toilet,
      wrench: Wrench,
      hammer: Hammer,
      "paint-roller": PaintRoller,
      paintbrush: Paintbrush,
      trees: Trees,
      flower: Flower,
      leaf: Leaf,
      sprout: Sprout,
      fence: Fence,
    },
  },
  {
    label: "Food & Dining",
    icons: {
      utensils: Utensils,
      coffee: Coffee,
      pizza: Pizza,
      beer: Beer,
      wine: Wine,
      "ice-cream": IceCreamCone,
      cake: Cake,
      croissant: Croissant,
      soup: Soup,
      fish: Fish,
      beef: Beef,
      apple: Apple,
      carrot: Carrot,
    },
  },
  {
    label: "Shopping",
    icons: {
      store: Store,
      package: Package,
      shirt: Shirt,
      shoes: Footprints,
      gem: Gem,
      watch: Watch,
      gift: Gift,
      tag: Tag,
      percent: Percent,
    },
  },
  {
    label: "Transport & Travel",
    icons: {
      bus: Bus,
      train: TrainFront,
      fuel: Fuel,
      bike: Bike,
      ship: Ship,
      parking: ParkingCircle,
      route: Route,
      "map-pin": MapPin,
      navigation: Navigation,
      umbrella: Umbrella,
      "cloud-rain": CloudRain,
      sun: Sun,
      snowflake: Snowflake,
      luggage: Luggage,
      compass: Compass,
      globe: Globe,
      tent: Tent,
      mountain: Mountain,
      "palm-tree": Palmtree,
      sailboat: Sailboat,
      anchor: Anchor,
    },
  },
  {
    label: "Health & Family",
    icons: {
      stethoscope: Stethoscope,
      pill: Pill,
      syringe: Syringe,
      cross: Cross,
      activity: Activity,
      dumbbell: Dumbbell,
      glasses: Glasses,
      smile: Smile,
      baby: Baby,
      dog: Dog,
      cat: Cat,
      "paw-print": PawPrint,
      bone: Bone,
      bird: Bird,
      users: Users,
      user: User,
      heart: Heart,
      church: Church,
    },
  },
  {
    label: "Entertainment",
    icons: {
      film: Film,
      music: Music,
      "music-note": Music2,
      gamepad: Gamepad,
      "gamepad-2": Gamepad2,
      ticket: Ticket,
      party: PartyPopper,
      camera: Camera,
      popcorn: Popcorn,
      dice: Dice5,
      palette: Palette,
    },
  },
  {
    label: "Education & Work",
    icons: {
      book: Book,
      "book-open": BookOpen,
      "graduation-cap": GraduationCap,
      backpack: Backpack,
      pencil: Pencil,
      school: School,
      briefcase: Briefcase,
      laptop: Laptop,
      smartphone: Smartphone,
      headphones: Headphones,
      monitor: Monitor,
      printer: Printer,
      "hard-drive": HardDrive,
    },
  },
  {
    label: "Finance",
    icons: {
      wallet: Wallet,
      "credit-card": CreditCard,
      banknote: Banknote,
      coins: Coins,
      "trending-up": TrendingUp,
      "trending-down": TrendingDown,
      "line-chart": LineChart,
      "bar-chart": BarChart3,
      calculator: Calculator,
      "dollar-sign": DollarSign,
      euro: Euro,
      vault: Vault,
      "hand-coins": HandCoins,
    },
  },
  {
    label: "Misc",
    icons: {
      "folder-open": FolderOpen,
      archive: Archive,
      boxes: Boxes,
      recycle: Recycle,
      truck: Truck,
      bolt: Bolt,
      settings: Settings,
      star: Star,
      sparkles: Sparkles,
      award: Award,
      trophy: Trophy,
      target: Target,
      flag: Flag,
      shield: Shield,
      "shield-check": ShieldCheck,
      scale: Scale,
      scissors: Scissors,
      brush: Brush,
      wand: Wand2,
      bell: Bell,
      phone: Phone,
      mail: Mail,
      message: MessageCircle,
      video: Video,
      radio: Radio,
      newspaper: Newspaper,
    },
  },
];

const CATEGORY_ICONS: Record<string, LucideIcon> = Object.fromEntries(
  CATEGORY_ICON_GROUPS.flatMap((group) => Object.entries(group.icons)),
);

/**
 * Resolve a stored icon key to a lucide component. Unknown, legacy (emoji),
 * or undefined values fall back to `Folder` so nothing renders broken.
 */
function resolveCategoryIcon(key?: string): LucideIcon {
  if (key && Object.prototype.hasOwnProperty.call(CATEGORY_ICONS, key)) {
    return CATEGORY_ICONS[key];
  }
  return Folder;
}

export type CategoryIconTileSize = "2xs" | "xs" | "sm" | "md" | "lg";

const tileSizes: Record<CategoryIconTileSize, string> = {
  "2xs": "h-4 w-4 rounded-[4px]",
  xs: "h-5 w-5 rounded-md",
  sm: "h-8 w-8 rounded-lg",
  md: "h-10 w-10 rounded-xl",
  lg: "h-12 w-12 rounded-xl",
};

const glyphSizes: Record<CategoryIconTileSize, number> = {
  "2xs": 11,
  xs: 12,
  sm: 16,
  md: 20,
  lg: 24,
};

export interface CategoryIconTileProps extends React.HTMLAttributes<HTMLSpanElement> {
  /** Stored icon key; unknown/legacy values fall back to Folder. */
  icon?: string;
  size?: CategoryIconTileSize;
}

/**
 * Renders the resolved category glyph in `text-brand-category` inside a violet
 * `bg-brand-category/10` tile (single violet tile per ADR 0007 — no palette).
 * Self-contained and reused by other widgets.
 */
export function CategoryIconTile({
  icon,
  size = "md",
  className,
  ...props
}: CategoryIconTileProps) {
  const known =
    icon && Object.prototype.hasOwnProperty.call(CATEGORY_ICONS, icon);
  const label = known ? icon : "other";
  return (
    <span
      role="img"
      aria-label={label}
      className={cn(
        "inline-grid place-items-center shrink-0 bg-brand-category/10 text-brand-category",
        tileSizes[size],
        className,
      )}
      {...props}
    >
      {createElement(resolveCategoryIcon(icon), {
        size: glyphSizes[size],
        "aria-hidden": true,
      })}
    </span>
  );
}
